## This file was generated by taghandlerwriter.pl script.
##
## Copyright 2011 Krzesimir Nowak
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
##

package Gir::Api::Member;

use strict;
use warnings;

use parent qw(Gir::Api::Common::Base);



sub new ($)
{
  my $type = shift;
  my $class = (ref ($type) or $type or 'Gir::Api::Member');
  my $groups =
  [

  ];
  my $attributes =
  [
    'attribute_c_identifier',
    'attribute_glib_nick',
    'attribute_name',
    'attribute_value'
  ];
  my $self = $class->SUPER::new ($groups, $attributes);

  bless ($self, $class);
  return $self;
}

sub new_with_params ($$)
{
  my ($type, $params) = @_;
  my $self = Gir::Api::Member::new ($type);

  $self->set_a_c_identifier($params->{'c:identifier'});
  $self->set_a_glib_nick($params->{'glib:nick'});
  $self->set_a_name($params->{'name'});
  $self->set_a_value($params->{'value'});

  return $self;
}









sub get_a_c_identifier ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_c_identifier');
}

sub get_a_glib_nick ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_glib_nick');
}

sub get_a_name ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_name');
}

sub get_a_value ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_value');
}


sub set_a_c_identifier ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_c_identifier', $value);
}

sub set_a_glib_nick ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_glib_nick', $value);
}

sub set_a_name ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_name', $value);
}

sub set_a_value ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_value', $value);
}


1; # indicate proper module load.
