## This file was generated by taghandlerwriter.pl script.
##
## Copyright 2011, 2012 Krzesimir Nowak
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
##

package Gir::Api::Repository;

use strict;
use warnings;

use parent qw (Gir::Api::Common::Base);

use Gir::Api::CInclude;
use Gir::Api::Include;
use Gir::Api::Namespace;
use Gir::Api::Package;

sub new ($)
{
  my $type = shift;
  my $class = (ref $type or $type or 'Gir::Api::Repository');
  my $groups =
  [
    'group_c_include',
    'group_include',
    'group_namespace',
    'group_package'
  ];
  my $attributes =
  [
    'attribute_version',
    'attribute_xmlns',
    'attribute_xmlns_c',
    'attribute_xmlns_glib'
  ];
  my $self = $class->SUPER::new ($groups, $attributes);

  bless $self, $class;
  return $self;
}

sub new_with_params ($$)
{
  my ($type, $params) = @_;
  my $self = Gir::Api::Repository::new $type;

  $self->set_a_version ($params->{'version'});
  $self->set_a_xmlns ($params->{'xmlns'});
  $self->set_a_xmlns_c ($params->{'xmlns:c'});
  $self->set_a_xmlns_glib ($params->{'xmlns:glib'});

  return $self;
}

sub get_g_c_include_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_c_include', $name);
}

sub get_g_include_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_include', $name);
}

sub get_g_namespace_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_namespace', $name);
}

sub get_g_package_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_package', $name);
}


sub get_g_c_include_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_c_include', $index);
}

sub get_g_include_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_include', $index);
}

sub get_g_namespace_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_namespace', $index);
}

sub get_g_package_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_package', $index);
}


sub get_g_c_include_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_c_include');
}

sub get_g_include_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_include');
}

sub get_g_namespace_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_namespace');
}

sub get_g_package_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_package');
}


sub add_g_c_include ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_c_include', $member_name, $member);
}

sub add_g_include ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_include', $member_name, $member);
}

sub add_g_namespace ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_namespace', $member_name, $member);
}

sub add_g_package ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_package', $member_name, $member);
}


sub get_a_version ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_version');
}

sub get_a_xmlns ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_xmlns');
}

sub get_a_xmlns_c ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_xmlns_c');
}

sub get_a_xmlns_glib ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_xmlns_glib');
}


sub set_a_version ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_version', $value);
}

sub set_a_xmlns ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_xmlns', $value);
}

sub set_a_xmlns_c ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_xmlns_c', $value);
}

sub set_a_xmlns_glib ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_xmlns_glib', $value);
}


1; # indicate proper module load.
