## This file was generated by taghandlerwriter.pl script.
##
## Copyright 2011 Krzesimir Nowak
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
##

package Gir::Api::TopLevel;

use strict;
use warnings;

use parent qw(Gir::Api::Common::Base);

use Gir::Api::Repository;

sub new ($)
{
  my $type = shift;
  my $class = (ref ($type) or $type or 'Gir::Api::TopLevel');
  my $groups =
  [
    'group_repository'
  ];
  my $attributes =
  [

  ];
  my $self = $class->SUPER::new ($groups, $attributes);

  bless ($self, $class);
  return $self;
}

sub new_with_params ($$)
{
  my ($type, $params) = @_;
  my $self = Gir::Api::TopLevel::new ($type);



  return $self;
}

sub get_g_repository_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_repository', $name);
}


sub get_g_repository_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_repository', $index);
}


sub get_g_repository_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_repository');
}


sub add_g_repository ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_repository', $member_name, $member);
}






1; # indicate proper module load.
