## This file was generated by taghandlerwriter.pl script.
##
## Copyright 2011, 2012 Krzesimir Nowak
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
##

package Gir::Api::Type;

use strict;
use warnings;

use parent qw (Gir::Api::Common::Base);

use Gir::Api::Array;
use Gir::Api::Type;
use Gir::Api::Varargs;

sub new ($)
{
  my $type = shift;
  my $class = (ref $type or $type or 'Gir::Api::Type');
  my $groups =
  [
    'group_array',
    'group_type',
    'group_varargs'
  ];
  my $attributes =
  [
    'attribute_c_type',
    'attribute_foreign',
    'attribute_name'
  ];
  my $self = $class->SUPER::new ($groups, $attributes);

  bless $self, $class;
  return $self;
}

sub new_with_params ($$)
{
  my ($type, $params) = @_;
  my $self = Gir::Api::Type::new $type;

  $self->set_a_c_type ($params->{'c:type'});
  $self->set_a_foreign ($params->{'foreign'});
  $self->set_a_name ($params->{'name'});

  return $self;
}

sub get_g_array_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_array', $name);
}

sub get_g_type_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_type', $name);
}

sub get_g_varargs_by_name ($$)
{
  my ($self, $name) = @_;

  return $self->_get_group_member_by_name ('group_varargs', $name);
}


sub get_g_array_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_array', $index);
}

sub get_g_type_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_type', $index);
}

sub get_g_varargs_by_index ($$)
{
  my ($self, $index) = @_;

  return $self->_get_group_member_by_index ('group_varargs', $index);
}


sub get_g_array_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_array');
}

sub get_g_type_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_type');
}

sub get_g_varargs_count ($)
{
  my $self = shift;

  return $self->_get_group_member_count ('group_varargs');
}


sub add_g_array ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_array', $member_name, $member);
}

sub add_g_type ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_type', $member_name, $member);
}

sub add_g_varargs ($$$)
{
  my ($self, $member_name, $member) = @_;

  $self->_add_member_to_group ('group_varargs', $member_name, $member);
}


sub get_a_c_type ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_c_type');
}

sub get_a_foreign ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_foreign');
}

sub get_a_name ($)
{
  my ($self) = @_;

  return $self->_get_attribute ('attribute_name');
}


sub set_a_c_type ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_c_type', $value);
}

sub set_a_foreign ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_foreign', $value);
}

sub set_a_name ($$)
{
  my ($self, $value) = @_;

  $self->_set_attribute ('attribute_name', $value);
}


1; # indicate proper module load.
