# Currently we track two versions of gcc: gcc-10 and gcc-11.

image: debian:testing

stages:
  - deps
  - build
  - deploy

variables:
  MESON_DEPS: g++
              gettext
              git
              yelp-tools
              gtk-doc-tools
              python3-pygments
              python3-setuptools
              libglib2.0-dev
              mm-common
              libxml-libxml-perl
              meson
              ninja-build
              glib-networking
  GIO_EXTRA_MODULES: "/usr/lib/x86_64-linux-gnu/gio/modules"
  GIT_SUBMODULE_STRATEGY: normal

.build_default:
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update && apt -y upgrade && apt -y install $DEPENDENCIES

# Clear the cache manually.
clear_cache:
  stage: deps
  when: manual
  script:
    - echo Clearing the build-deps cache
  cache:
    key: build-deps
    paths:
      - libsigc/
    policy: push

build_deps:
  extends: .build_default
  stage: deps
  variables:
    DEPENDENCIES: $MESON_DEPS
  script:
    # Build and cache dependencies that can't be installed with apt.
    # Build libsigc++3
    - echo HOME= $HOME
    - if test ! -d libsigc; then
    - git clone --branch 3.2.0 --depth 1 https://github.com/libsigcplusplus/libsigcplusplus.git libsigc
    - cd libsigc
    - mkdir _build && cd _build
    - meson --prefix=/usr --libdir=lib -Dbuild-documentation=false -Dbuild-examples=false -Dbuildtype=release
    - meson compile
    - meson configure --prefix=$HOME/install
    - cd ../..
    - fi
    - cd libsigc/_build
    - meson install
  cache:
    key: build-deps
    paths:
      - libsigc/
    policy: pull-push
  artifacts:
    paths:
      - install/
    expire_in: 1 day

autotools_build:
  extends: .build_default
  stage: build
  variables:
    DEPENDENCIES: $MESON_DEPS make autoconf
  script:
    - echo HOME= $HOME
    - ./autogen.sh --enable-warnings=fatal --prefix=/usr
    - make
    - make check
    - make install
  allow_failure: true


release_gcc_10_build:
  extends: .build_default
  stage: build
  variables:
    DEPENDENCIES: $MESON_DEPS g++-10
  script:
    - echo HOME= $HOME
    - mkdir _build && cd _build
    # -Ddebug=false + -Doptimization=3 correspond to -Dbuildtype=release
    - CC=gcc-10 CXX=g++-10 meson --prefix=/usr --libdir=lib -Ddebug=false -Doptimization=3 -Dwarnings=fatal
    - meson compile
    - meson test
    - meson install
  artifacts:
    when: always
    paths:
      - _build/docs/reference

# Publish reference documentation at gnome.pages.gitlab.gnome.org/glibmm
pages:
  stage: deploy
  needs: [release_gcc_10_build]
  script:
    - mkdir public
    - mv _build/docs/reference/html/* public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
