# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ubuntu:devel

stages:
  - build

variables:
  DEPENDENCIES: g++
                gettext
                git
                yelp-tools
                gtk-doc-tools
                make
                autoconf
                python3-pygments
                python3-setuptools
                libglib2.0-dev
                mm-common
                libxml-libxml-perl

  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt update && apt -y upgrade && apt -y install $DEPENDENCIES
  - git clone --branch 3.0.0 https://github.com/libsigcplusplus/libsigcplusplus libsigc
  - cd libsigc
  - ./autogen.sh --prefix=/usr
  - make
  - make install && cd ..

library_build:
  stage: build
  script:
  - ./autogen.sh --prefix=/usr
  - make
  - make install

