INCLUDES = \
	-I$(top_builddir)/glib	-I$(top_srcdir)/glib	\
	-I$(top_builddir)/gio	-I$(top_srcdir)/gio	\
	$(GLIBMM_CFLAGS) $(GTHREAD_CFLAGS)

LIBS =	$(top_builddir)/glib/glibmm/libglibmm-2.4.la \
	$(top_builddir)/gio/giomm/libgiomm-2.4.la \
	$(GLIBMM_LIBS)

