
local_glibmm_lib	= $(top_builddir)/glib/glibmm/libglibmm-2.3.la

LIBS  = $(local_glibmm_lib) $(GLIBMM_LIBS)

all_includes	= -I$(top_builddir)/glib	-I$(top_srcdir)/glib	\
		  $(GLIBMM_CFLAGS)

DEFS			= @DEFS@
DEFAULT_INCLUDES	=
INCLUDES		= -I. -I$(srcdir) $(strip $(all_includes))

