## This file was generated by taghandlerwriter.pl script.
##
## Copyright 2011, 2012 Krzesimir Nowak
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
##

package Gir::Handlers::Common::Tags;

use strict;
use warnings;

use Gir::Handlers::Common::Misc;

sub get_alias_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['c:type', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1]
  ],
  @_;
}


sub get_array_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [
    ['c:type', undef],
    ['fixed-size', undef],
    ['length', undef],
    ['name', undef],
    ['zero-terminated', 1]
  ],
  @_;
}


sub get_attribute_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef],
    ['value', undef]
  ],
  [

  ],
  @_;
}


sub get_bitfield_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:type', undef],
    ['name', undef]
  ],
  [
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['glib:get-type', undef],
    ['glib:type-name', undef],
    ['introspectable', 1],
    ['version', undef]
  ],
  @_;
}


sub get_c_include_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [

  ],
  @_;
}


sub get_callback_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['c:type', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['throws', 0],
    ['version', undef]
  ],
  @_;
}


sub get_class_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:symbol-prefix', undef],
    ['glib:type-name', undef],
    ['name', undef]
  ],
  [
    ['abstract', 0],
    ['c:type', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['glib:fundamental', 0],
    ['glib:get-type', undef],
    ['glib:get-value-func', undef],
    ['glib:ref-func', undef],
    ['glib:set-value-func', undef],
    ['glib:type-struct', undef],
    ['glib:unref-func', undef],
    ['introspectable', 1],
    ['parent', undef],
    ['version', undef]
  ],
  @_;
}


sub get_constant_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:type', undef],
    ['name', undef],
    ['value', undef]
  ],
  [

  ],
  @_;
}


sub get_constructor_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['c:identifier', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['moved-to', undef],
    ['shadowed-by', undef],
    ['shadows', undef],
    ['throws', 0],
    ['version', undef]
  ],
  @_;
}


sub get_doc_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['xml:whitespace', 'preserve']
  ],
  [

  ],
  @_;
}


sub get_enumeration_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:type', undef],
    ['name', undef]
  ],
  [
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['glib:error-domain', undef],
    ['glib:get-type', undef],
    ['glib:type-name', undef],
    ['introspectable', 1],
    ['version', undef]
  ],
  @_;
}


sub get_field_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['bits', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['private', 0],
    ['readable', 1],
    ['writable', 0]
  ],
  @_;
}


sub get_function_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['c:identifier', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['moved-to', undef],
    ['shadowed-by', undef],
    ['shadows', undef],
    ['throws', 0],
    ['version', undef]
  ],
  @_;
}


sub get_glib_boxed_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['glib:name', undef]
  ],
  [
    ['c:symbol-prefix', undef],
    ['glib:get-type', undef],
    ['glib:type-name', undef]
  ],
  @_;
}


sub get_glib_signal_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['action', 0],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['detailed', 0],
    ['introspectable', 1],
    ['no-hooks', 0],
    ['no-recurse', 0],
    ['version', undef],
    ['when', undef]
  ],
  @_;
}


sub get_implements_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [

  ],
  @_;
}


sub get_include_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef],
    ['version', undef]
  ],
  [

  ],
  @_;
}


sub get_interface_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:symbol-prefix', undef],
    ['glib:type-name', undef],
    ['name', undef]
  ],
  [
    ['c:type', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['glib:get-type', undef],
    ['glib:type-struct', undef],
    ['introspectable', 1],
    ['version', undef]
  ],
  @_;
}


sub get_member_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:identifier', undef],
    ['name', undef],
    ['value', undef]
  ],
  [
    ['glib:nick', undef]
  ],
  @_;
}


sub get_method_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['c:identifier', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['moved-to', undef],
    ['shadowed-by', undef],
    ['shadows', undef],
    ['throws', 0],
    ['version', undef]
  ],
  @_;
}


sub get_namespace_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['c:identifier-prefixes', undef],
    ['c:symbol-prefixes', undef],
    ['name', undef],
    ['version', undef]
  ],
  [
    ['shared-library', undef]
  ],
  @_;
}


sub get_package_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [

  ],
  @_;
}


sub get_parameter_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [
    ['allow-none', 0],
    ['caller-allocates', 0],
    ['closure', undef],
    ['destroy', undef],
    ['direction', 'in'],
    ['name', undef],
    ['scope', undef],
    ['skip', 0],
    ['transfer-ownership', undef]
  ],
  @_;
}


sub get_parameters_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [

  ],
  @_;
}


sub get_prerequisite_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [

  ],
  @_;
}


sub get_property_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef],
    ['transfer-ownership', undef]
  ],
  [
    ['construct', 0],
    ['construct-only', 0],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['readable', 1],
    ['version', undef],
    ['writable', 0]
  ],
  @_;
}


sub get_record_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [
    ['c:symbol-prefix', undef],
    ['c:type', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['disguised', 0],
    ['foreign', 0],
    ['glib:get-type', undef],
    ['glib:is-gtype-struct-for', undef],
    ['glib:type-name', undef],
    ['introspectable', 1],
    ['name', undef],
    ['version', undef]
  ],
  @_;
}


sub get_repository_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['version', '1.2'],
    ['xmlns', 'http://www.gtk.org/introspection/core/1.0'],
    ['xmlns:c', 'http://www.gtk.org/introspection/c/1.0']
  ],
  [
    ['xmlns:glib', 'http://www.gtk.org/introspection/glib/1.0']
  ],
  @_;
}


sub get_return_value_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [
    ['skip', 0],
    ['transfer-ownership', undef]
  ],
  @_;
}


sub get_type_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [
    ['c:type', undef],
    ['foreign', 0],
    ['name', undef]
  ],
  @_;
}


sub get_union_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [
    ['c:symbol-prefix', undef],
    ['c:type', undef],
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['glib:get-type', undef],
    ['glib:type-name', undef],
    ['introspectable', 1],
    ['name', undef],
    ['version', undef]
  ],
  @_;
}


sub get_varargs_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [

  ],
  [

  ],
  @_;
}


sub get_virtual_method_params (%)
{
  return Gir::Handlers::Common::Misc::extract_values
  [
    ['name', undef]
  ],
  [
    ['deprecated', undef],
    ['deprecated-version', undef],
    ['introspectable', 1],
    ['invoker', undef],
    ['throws', 0],
    ['version', undef]
  ],
  @_;
}


1; # indicate proper module load.
